//
//  Gloss.swift
//  Prompt Playground
//
//  Built-in TEST TASK — interlinear gloss. Everything gloss-specific (input shape, the hybrid
//  deterministic+model pipeline, the typed result DTOs, the headless + dynamic-lane runners, and the
//  objective evaluator) lives under one `Gloss` namespace so the generic ops core
//  (Runner/RunPipeline/Evaluator/Experiment) stays task-agnostic. A fixture, not core.
//  NO #Playground block — Xcode auto-runs those and crashes/re-instantiates the model.
//
//  The on-device model only ANNOTATES a deterministically segmented word list (NLTokenizer owns the
//  surfaces — LanguageTools.enrich); the model-facing schema is built at RUNTIME (Pipeline) as a
//  DynamicGenerationSchema pinned to exactly the selected word count, so each gloss binds to its word
//  and the count can't drift. See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.
//

import Foundation
import FoundationModels

enum Gloss {

    // MARK: - Input
    struct Input: Codable, Equatable, Sendable {
        var sentence: String
        var learning: String   // language being learned (the sentence's language)
        var native: String     // user's language (translations land here)
    }

    // MARK: - Result DTOs (deterministic fields + model annotations; scored by `evaluate`)

    /// One merged gloss word: deterministic surface/lemma/pos/romanization (from LanguageTools.enrich)
    /// plus the model's in-context meaning. Plain DTO — not generated by the model directly.
    struct WordGen: Codable, Equatable {
        var surface: String
        var lemma: String
        var partOfSpeech: String
        var translation: String          // "" when the word was skipped (common enough for this proficiency)
        var romanization: String?
        var zipf: Double?                 // word-family frequency (Zipf, ≈1–8); nil if rarer than the bundled floor
        var glossed: Bool                 // false = skipped as already-known for this proficiency (no model gloss)
    }

    /// Merged gloss result rendered in the output pane and scored by `Gloss.evaluate`.
    struct Result: Codable, Equatable {
        var words: [WordGen]
        var sentenceTranslation: String
    }

    // MARK: - Template resolution
    /// Resolve {{learning}}/{{native}} (canonical) plus legacy {{source}}/{{target}} aliases.
    static func resolve(_ template: String, _ input: Input, proficiency: String = "intermediate") -> String {
        template
            .replacingOccurrences(of: "{{learning}}", with: input.learning)
            .replacingOccurrences(of: "{{native}}", with: input.native)
            .replacingOccurrences(of: "{{source}}", with: input.learning)
            .replacingOccurrences(of: "{{target}}", with: input.native)
            .replacingOccurrences(of: "{{proficiency}}", with: proficiency)
    }

    // MARK: - Metrics
    struct Metrics: Codable, Equatable, Sendable {
        var wordCount: Int
        var coverageRatio: Double           // share of source content words present among surfaces
        var hallucinationRate: Double       // share of surfaces NOT found in the source (lower better)
        var fieldCompleteness: Double       // required word fields + sentence translation non-empty
        var dedupRate: Double               // share of duplicate surfaces (lower better)
        var posPlausibility: Double         // share of partOfSpeech values in a known set
        var sentenceTranslationPresent: Bool
    }

    // MARK: - Objective evaluator
    /// Gloss output metrics. `sentence` is the learning-language input; `native` is where
    /// translations should land.
    static func evaluate(_ r: Result, sentence: String, native: String) -> (Metrics, onTargetLanguage: Double?) {
        let surfaces = r.words
            .map { Evaluators.normalize($0.surface) }
            .filter { !$0.isEmpty }
        let sourceWords = Set(LanguageTools.words(sentence).map(Evaluators.normalize).filter { !$0.isEmpty })
        let surfaceSet = Set(surfaces)

        let covered = sourceWords.isEmpty ? 0 : sourceWords.filter { surfaceSet.contains($0) }.count
        let coverage = sourceWords.isEmpty ? 0 : Double(covered) / Double(sourceWords.count)

        let hallucinated = surfaces.filter { !sourceWords.contains($0) }.count
        let halluc = surfaces.isEmpty ? 0 : Double(hallucinated) / Double(surfaces.count)

        let dedup = surfaces.isEmpty ? 0 : 1 - Double(surfaceSet.count) / Double(surfaces.count)

        var checks = 0, passed = 0
        for w in r.words {
            // Skipped (already-known) words legitimately have a blank translation — don't penalize it.
            var fields = [w.surface, w.lemma, w.partOfSpeech]
            if w.glossed { fields.append(w.translation) }
            for field in fields {
                checks += 1
                if !field.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { passed += 1 }
            }
        }
        checks += 1
        let transPresent = !r.sentenceTranslation.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        if transPresent { passed += 1 }
        let completeness = checks == 0 ? 0 : Double(passed) / Double(checks)

        let pos = r.words.map { $0.partOfSpeech.lowercased().trimmingCharacters(in: .whitespacesAndNewlines) }
        let posOK = pos.isEmpty ? 0 : Double(pos.filter { Evaluators.knownPOS.contains($0) }.count) / Double(pos.count)

        // Language check: the generated translations must be in the native language.
        var nativeTexts = [r.sentenceTranslation] + r.words.map(\.translation)
        nativeTexts = nativeTexts.filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
        let lang = LanguageTools.matchScore(nativeTexts, expected: native)

        let m = Metrics(wordCount: r.words.count, coverageRatio: coverage,
                        hallucinationRate: halluc, fieldCompleteness: completeness,
                        dedupRate: dedup, posPlausibility: posOK,
                        sentenceTranslationPresent: transPresent)
        return (m, lang)
    }

    // MARK: - Runtime-schema pipeline (the hybrid algorithm)
    // Inverted, hybrid flow: NLTokenizer / NLTagger / CFStringTokenizer own the word list, POS/lemma,
    // and romanization (LanguageTools.enrich); the model only annotates the SELECTED subset (proficiency
    // word-selection by bundled Zipf frequency). The model-facing schema is built at runtime — a
    // {surface, meaning} object array pinned to the selected count — so glosses bind to their word and
    // can't misalign; a default output-token cap prevents the runaway that overflowed the 4096 window.
    @MainActor
    enum Pipeline {
        struct Output {
            let result: Result           // merged DTO
            let promptSent: String       // the token-list prompt
        }

        private struct Item { var surface: String; var meaning: String; var pos: String? }
        private struct Annotation { var items: [Item]; var sentenceTranslation: String }

        static func run(sentence: String, learning: String, proficiency: Proficiency,
                        instructions: String, config: GenConfig) async throws -> Output {
            let tokens = LanguageTools.enrich(sentence, language: learning)
            // NLTagger covers POS for its 8 languages; for others the model supplies POS (vocabulary-constrained).
            let modelPOS = !(LanguageTools.language(named: learning).map(LanguageTools.taggedLanguages.contains) ?? false)

            // Proficiency word-selection: gloss only words BELOW the cutoff. Absent-from-list (rarer than the
            // bundled floor) ⇒ rare ⇒ gloss; nil cutoff (beginner) ⇒ gloss everything.
            let cutoff = proficiency.glossCutoff
            let glossIdx = tokens.indices.filter { i in
                guard let cutoff, let z = tokens[i].zipf else { return true }
                return z < cutoff
            }
            let m = glossIdx.count

            // The model always sees the FULL sentence (so the whole-sentence translation is accurate) plus the
            // numbered subset to explain. Sending only the subset's meanings is what shrinks output tokens.
            let list = glossIdx.enumerated().map { "\($0.offset + 1). \(tokens[$0.element].surface)" }.joined(separator: "\n")
            let prompt = m == 0 ? "Sentence:\n\(sentence)"
                                : "Sentence:\n\(sentence)\n\nWords to explain (in order):\n\(list)"

            var cfg = config
            if cfg.maximumResponseTokens == nil { cfg.maximumResponseTokens = 700 } // anti-runaway default
            let options = cfg.toOptions()
            let schema = try annotationSchema(count: m, includePOS: modelPOS)

            func annotate() async throws -> Annotation {
                let content = try await LanguageModelSession(instructions: instructions)
                    .respond(to: prompt, schema: schema, includeSchemaInPrompt: true, options: options).content
                guard let data = content.jsonString.data(using: .utf8),
                      let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                    return Annotation(items: [], sentenceTranslation: "")
                }
                let raw = (obj["words"] as? [[String: Any]]) ?? []
                let items = raw.map { Item(surface: $0["surface"] as? String ?? "",
                                           meaning: $0["meaning"] as? String ?? "",
                                           pos: $0["pos"] as? String) }
                return Annotation(items: items, sentenceTranslation: (obj["sentenceTranslation"] as? String) ?? "")
            }

            // Each gloss is bound to its word inside one JSON object, so the model can't cascade-shift the
            // way a bare parallel meanings[] did; retry once only if it still left most glosses blank.
            var ann = try await annotate()
            if m > 0, ann.items.filter({ $0.meaning.trimmingCharacters(in: .whitespaces).isEmpty }).count * 2 > m {
                ann = try await annotate()
            }

            // Merge: bind each returned entry to its token by the echoed surface (realigning if the model
            // drifts), falling back to positional so a non-matching echo never drops a selected word.
            func norm(_ s: String) -> String { s.lowercased().trimmingCharacters(in: .whitespaces) }
            let glossSet = Set(glossIdx)
            var meaningFor: [Int: String] = [:]
            var posFor: [Int: String] = [:]
            var cursor = 0
            for oi in glossIdx {
                let expected = norm(tokens[oi].surface)
                let pick: Int? = (cursor < ann.items.count && norm(ann.items[cursor].surface) == expected)
                    ? cursor
                    : ((cursor..<ann.items.count).first { norm(ann.items[$0].surface) == expected } ?? (cursor < ann.items.count ? cursor : nil))
                if let k = pick {
                    meaningFor[oi] = ann.items[k].meaning
                    posFor[oi] = ann.items[k].pos ?? ""
                    cursor = k + 1
                }
            }
            let words = tokens.enumerated().map { i, tok -> WordGen in
                let modelPos = posFor[i].flatMap { $0.isEmpty ? nil : $0 }
                return WordGen(
                    surface: tok.surface,
                    lemma: tok.lemma ?? tok.surface,                 // CJK: no NLTagger lemma → surface
                    partOfSpeech: tok.pos ?? modelPos ?? "other",
                    translation: meaningFor[i] ?? "",
                    romanization: tok.romanization,
                    zipf: tok.zipf,
                    glossed: glossSet.contains(i))
            }
            return Output(result: Result(words: words, sentenceTranslation: ann.sentenceTranslation),
                          promptSent: prompt)
        }

        /// Runtime schema: `meanings` (and, for non-NLTagger languages, `partsOfSpeech`) pinned to
        /// exactly `count` elements so the per-word arrays can't misalign; POS constrained to the vocabulary.
        private static func annotationSchema(count: Int, includePOS: Bool) throws -> GenerationSchema {
            func str() -> DynamicGenerationSchema { DynamicGenerationSchema(type: String.self) }
            var wordProps: [DynamicGenerationSchema.Property] = [
                .init(name: "surface", description: "The word being explained, copied exactly from the list", schema: str()),
                .init(name: "meaning", description: "In-context meaning of this word as one short gloss in the learner's native language", schema: str())
            ]
            if includePOS {
                wordProps.append(.init(name: "pos", description: "Part of speech of this word",
                                       schema: DynamicGenerationSchema(type: String.self, guides: [.anyOf(LanguageTools.posVocabulary)])))
            }
            let word = DynamicGenerationSchema(name: "GlossWord", properties: wordProps)
            var props: [DynamicGenerationSchema.Property] = []
            if count > 0 {   // no words selected (all already-known) ⇒ ask only for the sentence translation
                props.append(.init(name: "words", description: "One entry per given word, in the same order",
                                   schema: DynamicGenerationSchema(arrayOf: word, minimumElements: count, maximumElements: count)))
            }
            props.append(.init(name: "sentenceTranslation", description: "Natural translation of the whole sentence into the learner's native language", schema: str()))
            return try GenerationSchema(root: DynamicGenerationSchema(name: "Gloss", properties: props), dependencies: [])
        }
    }

    // MARK: - Headless runner (typed lane, one shot)
    @MainActor
    enum Runner {
        static func run(template: String, input: Input, config: GenConfig,
                        proficiency: Proficiency = .intermediate) async -> RunResultData {
            let resolved = Gloss.resolve(template, input, proficiency: proficiency.rawValue)
            let start = Date()
            do {
                let out = try await Pipeline.run(sentence: input.sentence, learning: input.learning,
                                                 proficiency: proficiency, instructions: resolved, config: config)
                let latency = millis(since: start)
                let outputJSON = prettyJSON(out.result)
                let (gloss, lang) = Gloss.evaluate(out.result, sentence: input.sentence, native: input.native)
                // Pipeline owns its sessions, so estimate context from the resolved text instead of a transcript.
                let context = TokenEstimator.estimate(resolved + "\n" + out.promptSent + "\n" + outputJSON)
                let metrics = RunMetrics(
                    decoded: true, errorType: nil, latencyMs: latency,
                    promptTokensEst: TokenEstimator.estimate(resolved + "\n" + out.promptSent),
                    outputTokensEst: TokenEstimator.estimate(outputJSON),
                    contextTokensEst: context, contextHeadroom: TokenEstimator.headroom(context),
                    onTargetLanguage: lang, gloss: gloss, roleplay: nil)
                let trace = RunTrace(stages: [
                    .variables(ctx: ["sentence": input.sentence, "learning": input.learning, "native": input.native],
                               keys: ["sentence", "learning", "native"]),
                    .prompt(instructions: resolved, prompt: out.promptSent, schemaInjected: true),
                    .model(output: outputJSON, ms: latency, ttftMs: nil, tokensPerSec: nil, schemaInjected: true),
                ])
                return RunResultData(outputJSON: outputJSON, turnsJSON: nil, errorText: nil, metrics: metrics, trace: trace)
            } catch {
                let (type, text) = classify(error)
                return RunResultData(outputJSON: "", turnsJSON: nil, errorText: text,
                                     metrics: .failure(type, latencyMs: millis(since: start)))
            }
        }
    }

    // MARK: - Dynamic-lane runner (custom SchemaDef)
    @MainActor
    static func runDynamic(template: String, input: Input, def: SchemaDef, config: GenConfig) async -> RunResultData {
        let resolved = Gloss.resolve(template, input)
        let userPrompt = "Sentence: \(input.sentence)"
        let session = LanguageModelSession(instructions: resolved)
        let start = Date()
        do {
            let content = try await DynamicRun.respond(session: session, prompt: userPrompt,
                                                       def: def, options: config.toOptions())
            let latency = millis(since: start)
            let outputJSON = prettyJSONString(content.jsonString)
            let context = TokenEstimator.estimate(session.transcript)
            let metrics = RunEvaluator.metrics(json: outputJSON, decoded: true, latencyMs: latency,
                                               resolvedPrompt: resolved + "\n" + userPrompt,
                                               expectedLanguage: input.native, context: context)
            let trace = RunTrace(stages: [
                .variables(ctx: ["sentence": input.sentence, "learning": input.learning, "native": input.native],
                           keys: ["sentence", "learning", "native"]),
                .prompt(instructions: resolved, prompt: userPrompt, schemaInjected: true),
                .model(output: outputJSON, ms: latency, ttftMs: nil, tokensPerSec: nil, schemaInjected: true),
            ])
            return RunResultData(outputJSON: outputJSON, turnsJSON: nil, errorText: nil, metrics: metrics, trace: trace)
        } catch {
            let (type, text) = classify(error)
            return RunResultData(outputJSON: "", turnsJSON: nil, errorText: text,
                                 metrics: .failure(type, latencyMs: millis(since: start)))
        }
    }
}
