//
//  GlossPlayground.swift
//  Prompt Playground
//
//  Core of the Foundation Models test bench: @Generable schemas, the prompt-preset
//  registry, and the run engine. NO #Playground block — Xcode auto-runs those and
//  crashes/re-instantiates the model. Drive everything from the SwiftUI app instead.
//

import Foundation
import Observation
import FoundationModels

// MARK: - Schemas
// The on-device model only ANNOTATES a pre-segmented word list — deterministic NLTokenizer owns
// the surfaces (LanguageTools.enrich); it never produces the word list itself. The model-facing
// schema is built at RUNTIME (GlossPipeline) as a DynamicGenerationSchema so the `meanings` array
// can be pinned to exactly N elements (one per token). A typed @Generable can't express a runtime
// length, and eval showed an unpinned array silently misaligns (e.g. 2 meanings for 7 words).
// GlossWordGen / GlossResultGen are the MERGED DTOs (deterministic fields + model annotations),
// rendered as JSON in the output pane and scored by Evaluators.gloss.
// See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.

/// One merged gloss word: deterministic surface/lemma/pos/romanization (from LanguageTools.enrich)
/// plus the model's in-context meaning. Plain DTO — not generated by the model directly.
struct GlossWordGen: Codable, Equatable {
    var surface: String
    var lemma: String
    var partOfSpeech: String
    var translation: String
    var romanization: String?
}

/// Merged gloss result rendered in the output pane and scored by `Evaluators.gloss`.
struct GlossResultGen: Codable, Equatable {
    var words: [GlossWordGen]
    var sentenceTranslation: String
}

// MARK: - Preset registry
// A preset is a named, editable instructions template. The gloss run flow itself lives in
// GlossPipeline (shared by the single-shot tab and the headless Lab runner).
// Placeholders: {{learning}} (sentence language), {{native}} (explanations), {{proficiency}}.

struct PromptPreset: Identifiable {
    let id: String
    let name: String
    let defaultInstructions: String
}

let presets: [PromptPreset] = [
    PromptPreset(
        id: "gloss",
        name: "Gloss",
        defaultInstructions: """
        You are a {{learning}} tutor; the learner's native language is {{native}}. Learner level: {{proficiency}}.
        You are given the words of a {{learning}} sentence, already segmented, in order. For EACH word, in the \
        same order, give its single best meaning IN THIS SENTENCE (not its most common dictionary meaning) as one \
        short {{native}} gloss, plus its part of speech. Provide exactly one meaning per word; do not add, remove, \
        or reorder words. Then give a natural {{native}} translation of the whole sentence. Keep meanings simple \
        and literal for beginners; precise and idiomatic for advanced learners. If unsure of a word, give your \
        best single guess.
        """
    )
]

// MARK: - Gloss pipeline (shared by the single-shot tab + the headless Lab runner)
// Inverted, hybrid flow: NLTokenizer / NLTagger / CFStringTokenizer own the word list, POS/lemma,
// and romanization (LanguageTools.enrich); the model only annotates that fixed list. The model-facing
// schema is built at runtime, pinned to N elements, so the per-word arrays can't misalign; a default
// output-token cap prevents the runaway that overflowed the 4096 window in eval.
// See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.

@MainActor
enum GlossPipeline {
    struct Output {
        let result: GlossResultGen   // merged DTO
        let promptSent: String       // the token-list prompt
    }

    private struct Annotation { var meanings: [String]; var partsOfSpeech: [String]; var sentenceTranslation: String }

    static func run(sentence: String, learning: String, instructions: String,
                    config: GenConfig) async throws -> Output {
        let tokens = LanguageTools.enrich(sentence, language: learning)
        let n = tokens.count
        // NLTagger covers POS for its 8 languages; for others the model supplies POS (vocabulary-constrained).
        let modelPOS = !(LanguageTools.language(named: learning).map(LanguageTools.taggedLanguages.contains) ?? false)
        let list = tokens.enumerated().map { "\($0.offset + 1). \($0.element.surface)" }.joined(separator: "\n")
        let prompt = "Words (in order):\n\(list)"

        var cfg = config
        if cfg.maximumResponseTokens == nil { cfg.maximumResponseTokens = 700 } // anti-runaway default
        let options = cfg.toOptions()
        let schema = try annotationSchema(count: n, includePOS: modelPOS)

        func annotate() async throws -> Annotation {
            let content = try await LanguageModelSession(instructions: instructions)
                .respond(to: prompt, schema: schema, includeSchemaInPrompt: true, options: options).content
            guard let data = content.jsonString.data(using: .utf8),
                  let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                return Annotation(meanings: [], partsOfSpeech: [], sentenceTranslation: "")
            }
            return Annotation(meanings: (obj["meanings"] as? [String]) ?? [],
                              partsOfSpeech: (obj["partsOfSpeech"] as? [String]) ?? [],
                              sentenceTranslation: (obj["sentenceTranslation"] as? String) ?? "")
        }

        // The schema pins `meanings` to N elements, so counts can't drift; retry once only if the
        // model still left most glosses blank (a sign of a degenerate generation).
        var ann = try await annotate()
        if ann.meanings.filter({ $0.trimmingCharacters(in: .whitespaces).isEmpty }).count * 2 > max(n, 1) {
            ann = try await annotate()
        }

        let words = tokens.enumerated().map { i, tok in
            GlossWordGen(
                surface: tok.surface,
                lemma: tok.lemma ?? tok.surface,                                       // CJK: no NLTagger lemma → surface
                partOfSpeech: tok.pos ?? (i < ann.partsOfSpeech.count ? ann.partsOfSpeech[i] : "other"),
                translation: i < ann.meanings.count ? ann.meanings[i] : "",
                romanization: tok.romanization)
        }
        return Output(result: GlossResultGen(words: words, sentenceTranslation: ann.sentenceTranslation),
                      promptSent: prompt)
    }

    /// Runtime schema: `meanings` (and, for non-NLTagger languages, `partsOfSpeech`) pinned to
    /// exactly `count` elements so the per-word arrays can't misalign; POS constrained to the vocabulary.
    private static func annotationSchema(count: Int, includePOS: Bool) throws -> GenerationSchema {
        func str() -> DynamicGenerationSchema { DynamicGenerationSchema(type: String.self) }
        func pinned(_ leaf: DynamicGenerationSchema) -> DynamicGenerationSchema {
            DynamicGenerationSchema(arrayOf: leaf, minimumElements: count, maximumElements: count)
        }
        var props: [DynamicGenerationSchema.Property] = [
            .init(name: "meanings", description: "In-context meaning of each given word, in order, one per word", schema: pinned(str()))
        ]
        if includePOS {
            props.append(.init(name: "partsOfSpeech", description: "Part of speech of each given word, in order",
                               schema: pinned(DynamicGenerationSchema(type: String.self, guides: [.anyOf(LanguageTools.posVocabulary)]))))
        }
        props.append(.init(name: "sentenceTranslation", description: "Natural translation of the whole sentence into the learner's native language", schema: str()))
        return try GenerationSchema(root: DynamicGenerationSchema(name: "Gloss", properties: props), dependencies: [])
    }
}

// MARK: - Engine

@MainActor
@Observable
final class PlaygroundModel {
    var sentence: String = "Der Hund schläft."
    /// Values for the `{{name}}` placeholders in `instructions`, keyed by variable name.
    /// Seeded with the gloss preset's source/target languages.
    var variableValues: [String: String] = ["learning": "German", "native": "English", "proficiency": "intermediate"]
    var selectedPresetID: String
    var instructions: String

    // Surfaced in the output pane after a run.
    var resolvedInstructions: String = ""
    var userPrompt: String = ""
    var output: String = ""
    var errorText: String?
    var isRunning: Bool = false
    var elapsed: Double?

    // Generation config (additive: was Pipeline-only) + the dynamic-schema prototyping lane.
    var config = GenConfig()
    var useCustomSchema = false
    var customSchema: SchemaDef = .glossLike

    init() {
        let first = presets[0]
        selectedPresetID = first.id
        instructions = first.defaultInstructions
    }

    var selectedPreset: PromptPreset {
        presets.first { $0.id == selectedPresetID } ?? presets[0]
    }

    /// `{{name}}` with optional inner whitespace; the capture group is the trimmed variable name.
    /// One source of truth for both key detection and run-time substitution so they can't drift.
    static let variablePattern = /\{\{\s*([A-Za-z0-9_]+)\s*\}\}/

    /// Variable names referenced as `{{name}}` in `instructions`, in first-appearance order, deduped.
    /// Inner whitespace is trimmed, so `{{native}}`, `{{native }}`, and `{{ native }}` are one variable.
    var variableKeys: [String] {
        var seen = Set<String>()
        var keys: [String] = []
        for match in instructions.matches(of: Self.variablePattern) {
            let key = String(match.1)
            if seen.insert(key).inserted { keys.append(key) }
        }
        return keys
    }

    /// `{{…}}` fragments whose contents aren't a clean variable name (letters/digits/underscore).
    /// Surfaced as a warning so malformed tokens like `{{na me}}` or `{{}}` aren't dropped silently.
    var malformedTokens: [String] {
        var bad: [String] = []
        for match in instructions.matches(of: /\{\{(.*?)\}\}/) {
            let inner = String(match.1)
            if inner.trimmingCharacters(in: .whitespaces).wholeMatch(of: /[A-Za-z0-9_]+/) == nil {
                bad.append("{{\(inner)}}")
            }
        }
        return bad
    }

    /// Read accessors for the gloss task's language mapping (used when saving a dataset example).
    /// Canonical keys are learning/native; legacy source/target still accepted.
    var source: String { variableValues["learning"] ?? variableValues["source"] ?? "" }
    var target: String { variableValues["native"] ?? variableValues["target"] ?? "" }

    /// Reset the editable instructions to the chosen preset's default template.
    func loadPresetDefaults(for id: String) {
        if let p = presets.first(where: { $0.id == id }) {
            instructions = p.defaultInstructions
        }
    }

    var isModelAvailable: Bool {
        if case .available = SystemLanguageModel.default.availability { return true }
        return false
    }

    /// Non-nil when the model can't run; explains why.
    var availabilityMessage: String? {
        switch SystemLanguageModel.default.availability {
        case .available:
            return nil
        case .unavailable(let reason):
            switch reason {
            case .deviceNotEligible:
                return "Foundation Models isn't available on this Mac (requires Apple silicon)."
            case .appleIntelligenceNotEnabled:
                return "Apple Intelligence is off. Enable it in System Settings ▸ Apple Intelligence & Siri, and make sure the Siri language matches your device language."
            case .modelNotReady:
                return "The on-device model is still downloading. Try again shortly."
            @unknown default:
                return "Foundation Models is currently unavailable."
            }
        }
    }

    func run() async {
        guard !isRunning else { return }
        errorText = nil
        output = ""
        resolvedInstructions = ""
        userPrompt = ""
        elapsed = nil
        isRunning = true
        defer { isRunning = false }

        let resolved = instructions.replacing(Self.variablePattern) { match in
            variableValues[String(match.1)] ?? ""
        }
        resolvedInstructions = resolved

        // Fresh session per run so a prior run never biases the next (clean A/B testing).
        let start = Date()
        do {
            if useCustomSchema {
                let session = LanguageModelSession(instructions: resolved)
                let prompt = "Sentence: \(sentence)"
                userPrompt = prompt
                let content = try await DynamicRun.respond(session: session, prompt: prompt,
                                                           def: customSchema, options: config.toOptions())
                output = prettyJSONString(content.jsonString)
            } else {
                let out = try await GlossPipeline.run(sentence: sentence, learning: source,
                                                      instructions: resolved, config: config)
                userPrompt = out.promptSent
                output = prettyJSON(out.result)
            }
        } catch let e as SchemaWalker.ValidationError {
            errorText = "Schema error: \(e.localizedDescription)"
        } catch {
            errorText = "Generation failed: \(error.localizedDescription)"
        }
        elapsed = Date().timeIntervalSince(start)
    }
}
