//
//  GlossPlayground.swift
//  Prompt Playground
//
//  Core of the Foundation Models test bench: @Generable schemas, the prompt-preset
//  registry, and the run engine. NO #Playground block — Xcode auto-runs those and
//  crashes/re-instantiates the model. Drive everything from the SwiftUI app instead.
//

import Foundation
import Observation
import FoundationModels

// MARK: - Schemas
// The on-device model only ANNOTATES a deterministically segmented word list — NLTokenizer owns the
// surfaces (LanguageTools.enrich); the model never produces the list. The model-facing schema is built
// at RUNTIME (GlossPipeline) as a DynamicGenerationSchema: a `words` array of {surface, meaning} objects
// pinned to exactly the number of SELECTED words (proficiency word-selection), so each gloss is bound to
// its word and the count can't drift. A typed @Generable can't express a runtime length, and eval showed
// both an unpinned array and a bare parallel meanings[] misalign (count drift / cascade shift).
// GlossWordGen / GlossResultGen are the MERGED DTOs (deterministic fields + model annotations),
// rendered as JSON in the output pane and scored by Evaluators.gloss.
// See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.

/// One merged gloss word: deterministic surface/lemma/pos/romanization (from LanguageTools.enrich)
/// plus the model's in-context meaning. Plain DTO — not generated by the model directly.
struct GlossWordGen: Codable, Equatable {
    var surface: String
    var lemma: String
    var partOfSpeech: String
    var translation: String          // "" when the word was skipped (common enough for this proficiency)
    var romanization: String?
    var zipf: Double?                 // word-family frequency (Zipf, ≈1–8); nil if rarer than the bundled floor
    var glossed: Bool                 // false = skipped as already-known for this proficiency (no model gloss)
}

/// Merged gloss result rendered in the output pane and scored by `Evaluators.gloss`.
struct GlossResultGen: Codable, Equatable {
    var words: [GlossWordGen]
    var sentenceTranslation: String
}

// MARK: - Preset registry
// A preset is a named starting point for the GENERIC runner: an instructions template, a sample
// input, an optional pre/post hook pipeline, and an optional output schema. The "Gloss" preset is
// the canonical teaching example — it wires a Tokenize pre-hook (producing {{words}}) to a gloss
// prompt and a structured output schema, so a new user sees hooks + guided generation working
// together. Selecting a preset loads all four (instructions / input / hooks / schema).

struct PromptPreset: Identifiable {
    let id: String
    let name: String
    let defaultInstructions: String
    var defaultInput: String = ""
    var hooks: HookPipelineDef = .empty
    var useSchema: Bool = false
    var schema: SchemaDef? = nil
    /// Seed values for the preset's `{{name}}` variables, applied on load so a preset built around a
    /// specific language (e.g. the Korean CJK sample) arrives configured for it. nil ⇒ leave as-is.
    var defaultVariables: [String: String]? = nil
}

let presets: [PromptPreset] = [
    PromptPreset(
        id: "gloss",
        name: "Example: gloss (hooks + Guided Generation)",
        defaultInstructions: """
        You are a {{learning}} tutor; the learner's native language is {{native}}. Learner level: {{proficiency}}.
        Below is the {{learning}} sentence and a numbered list of its words. For EACH listed word, in the same \
        order, give its single best meaning IN THIS SENTENCE (not its most common dictionary meaning) as one short \
        {{native}} gloss. Also give a natural {{native}} translation of the WHOLE sentence.

        Words:
        {{words}}
        """,
        defaultInput: "Der Hund schläft.",
        hooks: HookPipelineDef(pre: [
            HookDef(op: .tokenizeWords, inputVar: "prompt", outputVar: "words",
                    params: ["language": "{{learning}}", "format": "numbered"])
        ]),
        useSchema: true,
        schema: .glossLike,
        defaultVariables: ["learning": "German", "native": "English", "proficiency": "intermediate"]
    ),
    PromptPreset(
        id: "cjk-gloss",
        name: "Example: CJK gloss — Korean (reading + Guided Generation)",
        defaultInstructions: """
        You are a {{learning}} tutor; the learner's native language is {{native}}. Learner level: {{proficiency}}.
        Below is a {{learning}} sentence and a numbered list of its words, each followed by its reading in \
        [brackets]. For EACH listed word, in the same order, give: its dictionary (base) form, its part of \
        speech, and its single best meaning IN THIS SENTENCE as one short {{native}} gloss. Copy each surface \
        and reading exactly as given — do not re-romanize. {{learning}} words are often conjugated or carry \
        particles; always give the dictionary form in {{learning}}'s OWN script (the same script as the \
        surface), NEVER the romanized reading.

        Example dictionary forms (different words, for guidance — do not include them in your answer):
          책을 [chaegeul] → 책   ·   읽었어요 [ilgeosseoyo] → 읽다   ·   학교에서 [hakgyoeseo] → 학교
        Each form is Hangul (책 · 읽다 · 학교), not the reading — particles dropped, verbs/adjectives in their \
        plain 다 form. Then give a natural {{native}} translation of the whole sentence and one or two short \
        grammar notes.

        Words:
        {{words}}
        """,
        defaultInput: "저는 커피를 주문하고 싶어요.",
        hooks: HookPipelineDef(pre: [
            HookDef(op: .enrichGloss, inputVar: "prompt", outputVar: "words",
                    params: ["language": "{{learning}}"])
        ]),
        useSchema: true,
        schema: .cjkGloss,
        defaultVariables: ["learning": "Korean", "native": "English", "proficiency": "intermediate"]
    ),
    PromptPreset(
        id: "cjk-morph-deep",
        name: "Example: CJK morphology — Korean (deep single pass)",
        defaultInstructions: """
        You are a {{learning}} morphology tutor; the learner's native language is {{native}}. Learner level: {{proficiency}}.
        Below is a {{learning}} sentence and a numbered list of its words, each followed by its reading in [brackets]. \
        For EACH listed word, in the same order, decompose it into morphemes and give its dictionary form. {{learning}} \
        verbs and adjectives are heavily conjugated and nouns carry particles — split the SURFACE into a stem plus every \
        ending/particle, and ALWAYS give the dictionary form in {{learning}}'s OWN script (the plain 다 form for verbs/ \
        adjectives), NEVER the romanized reading. Also give each word's part of speech, in-context meaning, and a short \
        usage example. Copy each surface and reading exactly as given — do not re-romanize.

        Worked examples (different words — do not copy them into your answer):
          • 만나서 → dictionaryForm 만나다 (verb). morphemes: 만나- [stem, "to meet"] + -아서 [ending, "connective 'and so'"].
          • 봤어요 → dictionaryForm 보다 (verb). morphemes: 보- [stem, "to see"] + -았- [ending, "past"] + -어요 [ending, \
        "polite informal 해요체"]. note: 보았어요 contracts to 봤어요. register: "polite informal (해요체)".
        Rule shown by these: strip EVERY ending back to the bare 다 form (만나서 → 만나다, NOT 만나서다; 봤어요 → 보다, NOT 봤다).

        Then give a natural {{native}} translation of the whole sentence and one or two short grammar notes.

        Words:
        {{words}}
        """,
        defaultInput: "어제 친구를 만나서 영화를 봤어요.",
        hooks: HookPipelineDef(pre: [
            HookDef(op: .enrichGloss, inputVar: "prompt", outputVar: "words",
                    params: ["language": "{{learning}}"])
        ]),
        useSchema: true,
        schema: .morphologyFull,
        defaultVariables: ["learning": "Korean", "native": "English", "proficiency": "intermediate"]
    ),
    PromptPreset(
        id: "blank",
        name: "Blank (start here)",
        defaultInstructions: "You are a helpful assistant.",
        defaultInput: ""
    ),
]

// MARK: - Gloss pipeline (shared by the single-shot tab + the headless Lab runner)
// Inverted, hybrid flow: NLTokenizer / NLTagger / CFStringTokenizer own the word list, POS/lemma,
// and romanization (LanguageTools.enrich); the model only annotates the SELECTED subset (proficiency
// word-selection by bundled Zipf frequency). The model-facing schema is built at runtime — a
// {surface, meaning} object array pinned to the selected count — so glosses bind to their word and
// can't misalign; a default output-token cap prevents the runaway that overflowed the 4096 window.
// See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.

@MainActor
enum GlossPipeline {
    struct Output {
        let result: GlossResultGen   // merged DTO
        let promptSent: String       // the token-list prompt
    }

    private struct Item { var surface: String; var meaning: String; var pos: String? }
    private struct Annotation { var items: [Item]; var sentenceTranslation: String }

    static func run(sentence: String, learning: String, proficiency: Proficiency,
                    instructions: String, config: GenConfig) async throws -> Output {
        let tokens = LanguageTools.enrich(sentence, language: learning)
        // NLTagger covers POS for its 8 languages; for others the model supplies POS (vocabulary-constrained).
        let modelPOS = !(LanguageTools.language(named: learning).map(LanguageTools.taggedLanguages.contains) ?? false)

        // Proficiency word-selection: gloss only words BELOW the cutoff. Absent-from-list (rarer than the
        // bundled floor) ⇒ rare ⇒ gloss; nil cutoff (beginner) ⇒ gloss everything.
        let cutoff = proficiency.glossCutoff
        let glossIdx = tokens.indices.filter { i in
            guard let cutoff, let z = tokens[i].zipf else { return true }
            return z < cutoff
        }
        let m = glossIdx.count

        // The model always sees the FULL sentence (so the whole-sentence translation is accurate) plus the
        // numbered subset to explain. Sending only the subset's meanings is what shrinks output tokens.
        let list = glossIdx.enumerated().map { "\($0.offset + 1). \(tokens[$0.element].surface)" }.joined(separator: "\n")
        let prompt = m == 0 ? "Sentence:\n\(sentence)"
                            : "Sentence:\n\(sentence)\n\nWords to explain (in order):\n\(list)"

        var cfg = config
        if cfg.maximumResponseTokens == nil { cfg.maximumResponseTokens = 700 } // anti-runaway default
        let options = cfg.toOptions()
        let schema = try annotationSchema(count: m, includePOS: modelPOS)

        func annotate() async throws -> Annotation {
            let content = try await LanguageModelSession(instructions: instructions)
                .respond(to: prompt, schema: schema, includeSchemaInPrompt: true, options: options).content
            guard let data = content.jsonString.data(using: .utf8),
                  let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                return Annotation(items: [], sentenceTranslation: "")
            }
            let raw = (obj["words"] as? [[String: Any]]) ?? []
            let items = raw.map { Item(surface: $0["surface"] as? String ?? "",
                                       meaning: $0["meaning"] as? String ?? "",
                                       pos: $0["pos"] as? String) }
            return Annotation(items: items, sentenceTranslation: (obj["sentenceTranslation"] as? String) ?? "")
        }

        // Each gloss is bound to its word inside one JSON object, so the model can't cascade-shift the
        // way a bare parallel meanings[] did; retry once only if it still left most glosses blank.
        var ann = try await annotate()
        if m > 0, ann.items.filter({ $0.meaning.trimmingCharacters(in: .whitespaces).isEmpty }).count * 2 > m {
            ann = try await annotate()
        }

        // Merge: bind each returned entry to its token by the echoed surface (realigning if the model
        // drifts), falling back to positional so a non-matching echo never drops a selected word.
        func norm(_ s: String) -> String { s.lowercased().trimmingCharacters(in: .whitespaces) }
        let glossSet = Set(glossIdx)
        var meaningFor: [Int: String] = [:]
        var posFor: [Int: String] = [:]
        var cursor = 0
        for oi in glossIdx {
            let expected = norm(tokens[oi].surface)
            let pick: Int? = (cursor < ann.items.count && norm(ann.items[cursor].surface) == expected)
                ? cursor
                : ((cursor..<ann.items.count).first { norm(ann.items[$0].surface) == expected } ?? (cursor < ann.items.count ? cursor : nil))
            if let k = pick {
                meaningFor[oi] = ann.items[k].meaning
                posFor[oi] = ann.items[k].pos ?? ""
                cursor = k + 1
            }
        }
        let words = tokens.enumerated().map { i, tok -> GlossWordGen in
            let modelPos = posFor[i].flatMap { $0.isEmpty ? nil : $0 }
            return GlossWordGen(
                surface: tok.surface,
                lemma: tok.lemma ?? tok.surface,                 // CJK: no NLTagger lemma → surface
                partOfSpeech: tok.pos ?? modelPos ?? "other",
                translation: meaningFor[i] ?? "",
                romanization: tok.romanization,
                zipf: tok.zipf,
                glossed: glossSet.contains(i))
        }
        return Output(result: GlossResultGen(words: words, sentenceTranslation: ann.sentenceTranslation),
                      promptSent: prompt)
    }

    /// Runtime schema: `meanings` (and, for non-NLTagger languages, `partsOfSpeech`) pinned to
    /// exactly `count` elements so the per-word arrays can't misalign; POS constrained to the vocabulary.
    private static func annotationSchema(count: Int, includePOS: Bool) throws -> GenerationSchema {
        func str() -> DynamicGenerationSchema { DynamicGenerationSchema(type: String.self) }
        var wordProps: [DynamicGenerationSchema.Property] = [
            .init(name: "surface", description: "The word being explained, copied exactly from the list", schema: str()),
            .init(name: "meaning", description: "In-context meaning of this word as one short gloss in the learner's native language", schema: str())
        ]
        if includePOS {
            wordProps.append(.init(name: "pos", description: "Part of speech of this word",
                                   schema: DynamicGenerationSchema(type: String.self, guides: [.anyOf(LanguageTools.posVocabulary)])))
        }
        let word = DynamicGenerationSchema(name: "GlossWord", properties: wordProps)
        var props: [DynamicGenerationSchema.Property] = []
        if count > 0 {   // no words selected (all already-known) ⇒ ask only for the sentence translation
            props.append(.init(name: "words", description: "One entry per given word, in the same order",
                               schema: DynamicGenerationSchema(arrayOf: word, minimumElements: count, maximumElements: count)))
        }
        props.append(.init(name: "sentenceTranslation", description: "Natural translation of the whole sentence into the learner's native language", schema: str()))
        return try GenerationSchema(root: DynamicGenerationSchema(name: "Gloss", properties: props), dependencies: [])
    }
}

// MARK: - Engine

@MainActor
@Observable
final class PlaygroundModel {
    /// The user message sent to the model. May itself contain `{{name}}` placeholders, and is
    /// exposed to pre-hooks as the `input` context key (e.g. a Tokenize hook reads it).
    var input: String = "Der Hund schläft."
    /// Values for the `{{name}}` placeholders in `instructions`/`input`, keyed by variable name.
    var variableValues: [String: String] = ["learning": "German", "native": "English", "proficiency": "intermediate"]
    var selectedPresetID: String
    var instructions: String

    /// Pre/post native-API hooks that run around the model call.
    var hooks: HookPipelineDef = .empty

    // Run results.
    var output: String = ""        // final output (after post-hooks)
    var errorText: String?
    var isRunning: Bool = false
    var elapsed: Double?
    /// The pipeline as ordered stages, updated live as a run proceeds (drives the right panel).
    var stages: [PipelineStage] = []

    // Generation config + the dynamic-schema prototyping lane.
    var config = GenConfig()
    var useCustomSchema = false
    var customSchema: SchemaDef = .glossLike

    /// One step of the run, shown as a card in the output pane.
    struct PipelineStage: Identifiable {
        enum Kind { case variables, preHook, prompt, model, postHook, finalOutput }
        enum Status { case running, ok, error }
        let id = UUID()
        let kind: Kind
        var title: String
        var status: Status
        var body: String = ""
        var ms: Int? = nil
        var note: String? = nil
    }

    init() {
        let first = presets[0]
        selectedPresetID = first.id
        instructions = first.defaultInstructions
        input = first.defaultInput
        hooks = first.hooks
        useCustomSchema = first.useSchema
        customSchema = first.schema ?? .glossLike
        if let v = first.defaultVariables { variableValues = v }
    }

    var selectedPreset: PromptPreset {
        presets.first { $0.id == selectedPresetID } ?? presets[0]
    }

    /// `{{name}}` matcher — the one shared `Vars` pattern, so detection and substitution can't drift.
    static let variablePattern = Vars.pattern

    // The mis-wiring guards live in `PromptAnalysis` (PlaygroundCore) so the Lab inspector and the
    // Datasets editor reuse the exact same logic; these just bind them to the live engine's fields.
    var variableKeys: [String] {
        PromptAnalysis.variableKeys(instructions: instructions, input: input, hooks: hooks)
    }
    /// True when the prompt references the Prompt-field token (`{{prompt}}` or legacy `{{input}}`) —
    /// drives a "provided by the Prompt field" hint so it isn't mistaken for an unfilled variable.
    var usesPromptToken: Bool {
        PromptAnalysis.usesPromptToken(instructions: instructions, input: input)
    }
    /// Variables produced by enabled hooks — shown as info in the Variables card, not editable.
    var hookOutputs: Set<String> { PromptAnalysis.hookOutputs(hooks) }
    /// `{{…}}` fragments in the instructions whose contents aren't a clean variable name.
    var malformedTokens: [String] { PromptAnalysis.malformedTokens(in: instructions) }
    /// Enabled pre-hooks whose `outputVar` is consumed nowhere (the `outputVar`-typo catcher).
    var unusedHookOutputs: [String] {
        PromptAnalysis.unusedHookOutputs(instructions: instructions, input: input, hooks: hooks)
    }

    /// Load the chosen preset's instructions, sample input, hook pipeline, and output schema.
    func loadPresetDefaults(for id: String) {
        guard let p = presets.first(where: { $0.id == id }) else { return }
        instructions = p.defaultInstructions
        input = p.defaultInput
        hooks = p.hooks
        useCustomSchema = p.useSchema
        if let s = p.schema { customSchema = s }
        if let v = p.defaultVariables { variableValues = v }
    }

    var isModelAvailable: Bool {
        if case .available = SystemLanguageModel.default.availability { return true }
        return false
    }

    /// Non-nil when the model can't run; explains why.
    var availabilityMessage: String? {
        switch SystemLanguageModel.default.availability {
        case .available:
            return nil
        case .unavailable(let reason):
            switch reason {
            case .deviceNotEligible:
                return "Foundation Models isn't available on this Mac (requires Apple silicon)."
            case .appleIntelligenceNotEnabled:
                return "Apple Intelligence is off. Enable it in System Settings ▸ Apple Intelligence & Siri, and make sure the Siri language matches your device language."
            case .modelNotReady:
                return "The on-device model is still downloading. Try again shortly."
            @unknown default:
                return "Foundation Models is currently unavailable."
            }
        }
    }

    /// Generic pipeline: variables → pre-hooks → final prompt → model (schema or text) → post-hooks.
    /// Stages are appended/updated on the MainActor between awaits so the right panel animates live.
    func run() async {
        guard !isRunning else { return }
        errorText = nil
        output = ""
        elapsed = nil
        stages = []
        isRunning = true
        defer { isRunning = false }
        let overallStart = Date()

        // 1) Variables — seed the run context. The Prompt field is exposed as {{prompt}} (canonical)
        //    and {{input}} (legacy alias) so older templates keep resolving.
        var ctx = variableValues
        ctx["prompt"] = input
        ctx["input"] = input
        stages.append(PipelineStage(kind: .variables, title: "Variables", status: .ok,
                                    body: contextPreview(ctx, keys: variableKeys + ["prompt"])))

        // 2) Pre-hooks — one at a time so the panel shows progress; each chains off the last.
        for hook in hooks.pre where hook.enabled {
            stages.append(PipelineStage(kind: .preHook, title: "Pre · \(hook.op.displayName)", status: .running))
            let i = stages.count - 1
            await Task.yield()
            let step = await HookEngine.runOne(hook, context: &ctx)
            stages[i].status = step.error == nil ? .ok : .error
            stages[i].ms = step.ms
            stages[i].note = note(for: step, outputVar: hook.outputVar)
            stages[i].body = step.error == nil
                ? (hook.outputVar.isEmpty ? (step.output ?? "") : "{{\(hook.outputVar)}} =\n\(step.output ?? "")")
                : ""
        }

        // 3) Final prompt — a single substitution pass against the merged context.
        let resolvedInstructions = Vars.substitute(instructions, ctx)
        let userPrompt = Vars.substitute(input, ctx)
        stages.append(PipelineStage(
            kind: .prompt, title: "Final prompt", status: .ok,
            body: "INSTRUCTIONS\n\(resolvedInstructions)\n\nPROMPT\n\(userPrompt)",
            note: promptStageNote(instructions: resolvedInstructions, prompt: userPrompt)))

        // 4) Model — fresh session per run so a prior run never biases the next (clean A/B testing).
        stages.append(PipelineStage(kind: .model, title: "Model output", status: .running))
        let mi = stages.count - 1
        await Task.yield()
        let modelStart = Date()
        var rawOutput = ""
        do {
            let session = LanguageModelSession(instructions: resolvedInstructions)
            var ttft: Int? = nil
            // Stream the response so the panel fills in live; the last snapshot is the complete output.
            if useCustomSchema {
                let schema = try SchemaBuilder.generationSchema(from: customSchema)
                for try await snapshot in session.streamResponse(to: userPrompt, schema: schema,
                                                                 includeSchemaInPrompt: true,
                                                                 options: config.toOptions()) {
                    if ttft == nil { ttft = millis(since: modelStart) }
                    rawOutput = prettyJSONString(snapshot.rawContent.jsonString)
                    stages[mi].body = rawOutput
                }
            } else {
                for try await snapshot in session.streamResponse(to: userPrompt, options: config.toOptions()) {
                    if ttft == nil { ttft = millis(since: modelStart) }
                    rawOutput = snapshot.content
                    stages[mi].body = rawOutput
                }
            }
            let modelMs = millis(since: modelStart)
            stages[mi].status = .ok
            stages[mi].ms = modelMs
            stages[mi].body = rawOutput
            var note = [useCustomSchema ? "Conforms to the Guided Generation schema (constrained decoding)" : "Free-text output (streamed)"]
            if let ttft { note.append("TTFT \(ttft) ms") }
            if let tps = tokensPerSec(rawOutput, ms: modelMs) { note.append(String(format: "~%.0f tok/s", tps)) }
            stages[mi].note = note.joined(separator: " · ")
        } catch let e as SchemaWalker.ValidationError {
            failModel(at: mi, "Schema error: \(e.localizedDescription)", since: modelStart, overall: overallStart)
            return
        } catch {
            failModel(at: mi, "Generation failed: \(error.localizedDescription)", since: modelStart, overall: overallStart)
            return
        }

        // 5) Post-hooks — thread the output through, live. Final output = last result (else model output).
        var finalOut = rawOutput
        var postCtx = ctx
        postCtx["output"] = rawOutput
        let hasPost = hooks.post.contains { $0.enabled }
        for hook in hooks.post where hook.enabled {
            stages.append(PipelineStage(kind: .postHook, title: "Post · \(hook.op.displayName)", status: .running))
            let i = stages.count - 1
            await Task.yield()
            let step = await HookEngine.runOne(hook, context: &postCtx, defaultInput: finalOut)
            if let o = step.output { finalOut = o; postCtx["output"] = o }
            stages[i].status = step.error == nil ? .ok : .error
            stages[i].ms = step.ms
            stages[i].note = note(for: step, outputVar: hook.outputVar, terminal: true)
            stages[i].body = step.error == nil ? (step.output ?? "") : ""
        }

        output = finalOut
        if hasPost {   // distinct final card only when a post-hook actually transformed the output
            stages.append(PipelineStage(kind: .finalOutput, title: "Final output", status: .ok, body: finalOut))
        }
        elapsed = Date().timeIntervalSince(overallStart)
    }

    /// A finished hook's stage note: its error if it failed, else a warning when it *succeeded* but
    /// produced empty output — so a downstream `{{var}}` (or, for a terminal post-hook, the final
    /// output) silently going blank is visible rather than mistaken for a real result.
    private func note(for step: HookStep, outputVar: String, terminal: Bool = false) -> String? {
        if let error = step.error { return error }
        guard (step.output ?? "").trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        if terminal { return "⚠︎ Produced empty output — the final output is now blank." }
        return outputVar.isEmpty ? nil : "⚠︎ Produced empty output — {{\(outputVar)}} resolves to blank."
    }

    /// Final-prompt stage note: the schema mode plus an estimated token-headroom reading, so an
    /// over-long prompt is visible *before* it trips the 4096-token window at runtime.
    private func promptStageNote(instructions: String, prompt: String) -> String {
        PromptAnalysis.headroomNote(instructions: instructions, prompt: prompt, schemaInjected: useCustomSchema)
    }

    private func failModel(at index: Int, _ message: String, since modelStart: Date, overall: Date) {
        errorText = message
        stages[index].status = .error
        stages[index].ms = millis(since: modelStart)
        stages[index].note = message
        elapsed = Date().timeIntervalSince(overall)
    }

    /// "{{key}} = value" lines for the given keys present in the context (the Variables stage body).
    private func contextPreview(_ ctx: [String: String], keys: [String]) -> String {
        let shown = keys.filter { ctx[$0]?.isEmpty == false }
        guard !shown.isEmpty else { return "—" }
        return shown.map { "{{\($0)}} = \(ctx[$0] ?? "")" }.joined(separator: "\n")
    }
}
