//
//  GlossPlayground.swift
//  Prompt Playground
//
//  Core of the Foundation Models test bench: @Generable schemas, the prompt-preset
//  registry, and the run engine. NO #Playground block — Xcode auto-runs those and
//  crashes/re-instantiates the model. Drive everything from the SwiftUI app instead.
//

import Foundation
import Observation
import FoundationModels

// MARK: - Schemas
// The on-device model only ANNOTATES a deterministically segmented word list — NLTokenizer owns the
// surfaces (LanguageTools.enrich); the model never produces the list. The model-facing schema is built
// at RUNTIME (GlossPipeline) as a DynamicGenerationSchema: a `words` array of {surface, meaning} objects
// pinned to exactly the number of SELECTED words (proficiency word-selection), so each gloss is bound to
// its word and the count can't drift. A typed @Generable can't express a runtime length, and eval showed
// both an unpinned array and a bare parallel meanings[] misalign (count drift / cascade shift).
// GlossWordGen / GlossResultGen are the MERGED DTOs (deterministic fields + model annotations),
// rendered as JSON in the output pane and scored by Evaluators.gloss.
// See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.

/// One merged gloss word: deterministic surface/lemma/pos/romanization (from LanguageTools.enrich)
/// plus the model's in-context meaning. Plain DTO — not generated by the model directly.
struct GlossWordGen: Codable, Equatable {
    var surface: String
    var lemma: String
    var partOfSpeech: String
    var translation: String          // "" when the word was skipped (common enough for this proficiency)
    var romanization: String?
    var zipf: Double?                 // word-family frequency (Zipf, ≈1–8); nil if rarer than the bundled floor
    var glossed: Bool                 // false = skipped as already-known for this proficiency (no model gloss)
}

/// Merged gloss result rendered in the output pane and scored by `Evaluators.gloss`.
struct GlossResultGen: Codable, Equatable {
    var words: [GlossWordGen]
    var sentenceTranslation: String
}

// MARK: - Preset registry
// A preset is a named, editable instructions template. The gloss run flow itself lives in
// GlossPipeline (shared by the single-shot tab and the headless Lab runner).
// Placeholders: {{learning}} (sentence language), {{native}} (explanations), {{proficiency}}.

struct PromptPreset: Identifiable {
    let id: String
    let name: String
    let defaultInstructions: String
}

let presets: [PromptPreset] = [
    PromptPreset(
        id: "gloss",
        name: "Gloss",
        defaultInstructions: """
        You are a {{learning}} tutor; the learner's native language is {{native}}. Learner level: {{proficiency}}.
        You are given a {{learning}} sentence and, below it, a numbered list of selected words from it (only the \
        words worth explaining for this learner — not every word). For EACH listed word, in the same order, output \
        an entry containing the word copied exactly and its single best meaning IN THIS SENTENCE (not its most \
        common dictionary meaning) as one short {{native}} gloss. Provide exactly one entry per listed word; do not \
        add, remove, or reorder them. Also give a natural {{native}} translation of the WHOLE sentence. Keep meanings \
        simple and literal for beginners; precise and idiomatic for advanced learners. If unsure, give your best guess.
        """
    )
]

// MARK: - Gloss pipeline (shared by the single-shot tab + the headless Lab runner)
// Inverted, hybrid flow: NLTokenizer / NLTagger / CFStringTokenizer own the word list, POS/lemma,
// and romanization (LanguageTools.enrich); the model only annotates the SELECTED subset (proficiency
// word-selection by bundled Zipf frequency). The model-facing schema is built at runtime — a
// {surface, meaning} object array pinned to the selected count — so glosses bind to their word and
// can't misalign; a default output-token cap prevents the runaway that overflowed the 4096 window.
// See docs/decisions/ADR-20260608-hybrid-gloss-pipeline.md.

@MainActor
enum GlossPipeline {
    struct Output {
        let result: GlossResultGen   // merged DTO
        let promptSent: String       // the token-list prompt
    }

    private struct Item { var surface: String; var meaning: String; var pos: String? }
    private struct Annotation { var items: [Item]; var sentenceTranslation: String }

    static func run(sentence: String, learning: String, proficiency: Proficiency,
                    instructions: String, config: GenConfig) async throws -> Output {
        let tokens = LanguageTools.enrich(sentence, language: learning)
        // NLTagger covers POS for its 8 languages; for others the model supplies POS (vocabulary-constrained).
        let modelPOS = !(LanguageTools.language(named: learning).map(LanguageTools.taggedLanguages.contains) ?? false)

        // Proficiency word-selection: gloss only words BELOW the cutoff. Absent-from-list (rarer than the
        // bundled floor) ⇒ rare ⇒ gloss; nil cutoff (beginner) ⇒ gloss everything.
        let cutoff = proficiency.glossCutoff
        let glossIdx = tokens.indices.filter { i in
            guard let cutoff, let z = tokens[i].zipf else { return true }
            return z < cutoff
        }
        let m = glossIdx.count

        // The model always sees the FULL sentence (so the whole-sentence translation is accurate) plus the
        // numbered subset to explain. Sending only the subset's meanings is what shrinks output tokens.
        let list = glossIdx.enumerated().map { "\($0.offset + 1). \(tokens[$0.element].surface)" }.joined(separator: "\n")
        let prompt = m == 0 ? "Sentence:\n\(sentence)"
                            : "Sentence:\n\(sentence)\n\nWords to explain (in order):\n\(list)"

        var cfg = config
        if cfg.maximumResponseTokens == nil { cfg.maximumResponseTokens = 700 } // anti-runaway default
        let options = cfg.toOptions()
        let schema = try annotationSchema(count: m, includePOS: modelPOS)

        func annotate() async throws -> Annotation {
            let content = try await LanguageModelSession(instructions: instructions)
                .respond(to: prompt, schema: schema, includeSchemaInPrompt: true, options: options).content
            guard let data = content.jsonString.data(using: .utf8),
                  let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                return Annotation(items: [], sentenceTranslation: "")
            }
            let raw = (obj["words"] as? [[String: Any]]) ?? []
            let items = raw.map { Item(surface: $0["surface"] as? String ?? "",
                                       meaning: $0["meaning"] as? String ?? "",
                                       pos: $0["pos"] as? String) }
            return Annotation(items: items, sentenceTranslation: (obj["sentenceTranslation"] as? String) ?? "")
        }

        // Each gloss is bound to its word inside one JSON object, so the model can't cascade-shift the
        // way a bare parallel meanings[] did; retry once only if it still left most glosses blank.
        var ann = try await annotate()
        if m > 0, ann.items.filter({ $0.meaning.trimmingCharacters(in: .whitespaces).isEmpty }).count * 2 > m {
            ann = try await annotate()
        }

        // Merge: bind each returned entry to its token by the echoed surface (realigning if the model
        // drifts), falling back to positional so a non-matching echo never drops a selected word.
        func norm(_ s: String) -> String { s.lowercased().trimmingCharacters(in: .whitespaces) }
        let glossSet = Set(glossIdx)
        var meaningFor: [Int: String] = [:]
        var posFor: [Int: String] = [:]
        var cursor = 0
        for oi in glossIdx {
            let expected = norm(tokens[oi].surface)
            let pick: Int? = (cursor < ann.items.count && norm(ann.items[cursor].surface) == expected)
                ? cursor
                : ((cursor..<ann.items.count).first { norm(ann.items[$0].surface) == expected } ?? (cursor < ann.items.count ? cursor : nil))
            if let k = pick {
                meaningFor[oi] = ann.items[k].meaning
                posFor[oi] = ann.items[k].pos ?? ""
                cursor = k + 1
            }
        }
        let words = tokens.enumerated().map { i, tok -> GlossWordGen in
            let modelPos = posFor[i].flatMap { $0.isEmpty ? nil : $0 }
            return GlossWordGen(
                surface: tok.surface,
                lemma: tok.lemma ?? tok.surface,                 // CJK: no NLTagger lemma → surface
                partOfSpeech: tok.pos ?? modelPos ?? "other",
                translation: meaningFor[i] ?? "",
                romanization: tok.romanization,
                zipf: tok.zipf,
                glossed: glossSet.contains(i))
        }
        return Output(result: GlossResultGen(words: words, sentenceTranslation: ann.sentenceTranslation),
                      promptSent: prompt)
    }

    /// Runtime schema: `meanings` (and, for non-NLTagger languages, `partsOfSpeech`) pinned to
    /// exactly `count` elements so the per-word arrays can't misalign; POS constrained to the vocabulary.
    private static func annotationSchema(count: Int, includePOS: Bool) throws -> GenerationSchema {
        func str() -> DynamicGenerationSchema { DynamicGenerationSchema(type: String.self) }
        var wordProps: [DynamicGenerationSchema.Property] = [
            .init(name: "surface", description: "The word being explained, copied exactly from the list", schema: str()),
            .init(name: "meaning", description: "In-context meaning of this word as one short gloss in the learner's native language", schema: str())
        ]
        if includePOS {
            wordProps.append(.init(name: "pos", description: "Part of speech of this word",
                                   schema: DynamicGenerationSchema(type: String.self, guides: [.anyOf(LanguageTools.posVocabulary)])))
        }
        let word = DynamicGenerationSchema(name: "GlossWord", properties: wordProps)
        var props: [DynamicGenerationSchema.Property] = []
        if count > 0 {   // no words selected (all already-known) ⇒ ask only for the sentence translation
            props.append(.init(name: "words", description: "One entry per given word, in the same order",
                               schema: DynamicGenerationSchema(arrayOf: word, minimumElements: count, maximumElements: count)))
        }
        props.append(.init(name: "sentenceTranslation", description: "Natural translation of the whole sentence into the learner's native language", schema: str()))
        return try GenerationSchema(root: DynamicGenerationSchema(name: "Gloss", properties: props), dependencies: [])
    }
}

// MARK: - Engine

@MainActor
@Observable
final class PlaygroundModel {
    var sentence: String = "Der Hund schläft."
    /// Values for the `{{name}}` placeholders in `instructions`, keyed by variable name.
    /// Seeded with the gloss preset's source/target languages.
    var variableValues: [String: String] = ["learning": "German", "native": "English", "proficiency": "intermediate"]
    var selectedPresetID: String
    var instructions: String

    // Surfaced in the output pane after a run.
    var resolvedInstructions: String = ""
    var userPrompt: String = ""
    var output: String = ""
    var errorText: String?
    var isRunning: Bool = false
    var elapsed: Double?

    // Generation config (additive: was Pipeline-only) + the dynamic-schema prototyping lane.
    var config = GenConfig()
    var useCustomSchema = false
    var customSchema: SchemaDef = .glossLike

    init() {
        let first = presets[0]
        selectedPresetID = first.id
        instructions = first.defaultInstructions
    }

    var selectedPreset: PromptPreset {
        presets.first { $0.id == selectedPresetID } ?? presets[0]
    }

    /// `{{name}}` with optional inner whitespace; the capture group is the trimmed variable name.
    /// One source of truth for both key detection and run-time substitution so they can't drift.
    static let variablePattern = /\{\{\s*([A-Za-z0-9_]+)\s*\}\}/

    /// Variable names referenced as `{{name}}` in `instructions`, in first-appearance order, deduped.
    /// Inner whitespace is trimmed, so `{{native}}`, `{{native }}`, and `{{ native }}` are one variable.
    var variableKeys: [String] {
        var seen = Set<String>()
        var keys: [String] = []
        for match in instructions.matches(of: Self.variablePattern) {
            let key = String(match.1)
            if seen.insert(key).inserted { keys.append(key) }
        }
        return keys
    }

    /// `{{…}}` fragments whose contents aren't a clean variable name (letters/digits/underscore).
    /// Surfaced as a warning so malformed tokens like `{{na me}}` or `{{}}` aren't dropped silently.
    var malformedTokens: [String] {
        var bad: [String] = []
        for match in instructions.matches(of: /\{\{(.*?)\}\}/) {
            let inner = String(match.1)
            if inner.trimmingCharacters(in: .whitespaces).wholeMatch(of: /[A-Za-z0-9_]+/) == nil {
                bad.append("{{\(inner)}}")
            }
        }
        return bad
    }

    /// Read accessors for the gloss task's language mapping (used when saving a dataset example).
    /// Canonical keys are learning/native; legacy source/target still accepted.
    var source: String { variableValues["learning"] ?? variableValues["source"] ?? "" }
    var target: String { variableValues["native"] ?? variableValues["target"] ?? "" }

    /// Reset the editable instructions to the chosen preset's default template.
    func loadPresetDefaults(for id: String) {
        if let p = presets.first(where: { $0.id == id }) {
            instructions = p.defaultInstructions
        }
    }

    var isModelAvailable: Bool {
        if case .available = SystemLanguageModel.default.availability { return true }
        return false
    }

    /// Non-nil when the model can't run; explains why.
    var availabilityMessage: String? {
        switch SystemLanguageModel.default.availability {
        case .available:
            return nil
        case .unavailable(let reason):
            switch reason {
            case .deviceNotEligible:
                return "Foundation Models isn't available on this Mac (requires Apple silicon)."
            case .appleIntelligenceNotEnabled:
                return "Apple Intelligence is off. Enable it in System Settings ▸ Apple Intelligence & Siri, and make sure the Siri language matches your device language."
            case .modelNotReady:
                return "The on-device model is still downloading. Try again shortly."
            @unknown default:
                return "Foundation Models is currently unavailable."
            }
        }
    }

    func run() async {
        guard !isRunning else { return }
        errorText = nil
        output = ""
        resolvedInstructions = ""
        userPrompt = ""
        elapsed = nil
        isRunning = true
        defer { isRunning = false }

        let resolved = instructions.replacing(Self.variablePattern) { match in
            variableValues[String(match.1)] ?? ""
        }
        resolvedInstructions = resolved

        // Fresh session per run so a prior run never biases the next (clean A/B testing).
        let start = Date()
        do {
            if useCustomSchema {
                let session = LanguageModelSession(instructions: resolved)
                let prompt = "Sentence: \(sentence)"
                userPrompt = prompt
                let content = try await DynamicRun.respond(session: session, prompt: prompt,
                                                           def: customSchema, options: config.toOptions())
                output = prettyJSONString(content.jsonString)
            } else {
                let prof = Proficiency(label: variableValues["proficiency"] ?? "")
                let out = try await GlossPipeline.run(sentence: sentence, learning: source,
                                                      proficiency: prof, instructions: resolved, config: config)
                userPrompt = out.promptSent
                output = prettyJSON(out.result)
            }
        } catch let e as SchemaWalker.ValidationError {
            errorText = "Schema error: \(e.localizedDescription)"
        } catch {
            errorText = "Generation failed: \(error.localizedDescription)"
        }
        elapsed = Date().timeIntervalSince(start)
    }
}
